module.exports = {
	cards: [
		{
			name: "Scrap Hulk",
			type: "Mech", 
			value: 1, 
			text: "Launch: Roll. This has that much health.",
			attack: "3",
			defense: "*",
		},
		{
			name: "Unstable Laz-Unit",
			type: "Mech", 
			value: 1, 
			text: "Roll at the start of your turn. This has that much attack until your next turn.",
			attack: "*",
			defense: "2",
		},
		{
			name: "Smoking Hulk",
			type: "Mech", 
			value: 2, 
			text: "You may burn 1 as a component to summon this",
			attack: "6",
			defense: "6",
		},
		{
			name: "Prototype",
			type: "Mech", 
			value: 1, 
			text: "When used to summon a mech, this counts as two components",
			attack: "1",
			defense: "1",
		},
		{
			name: "Warmachine",
			type: "Mech", 
			value: 2, 
			attack: "10",
			defense: "10",
		},
		{
			name: "Ferromancer",
			type: "Mage", 
			value: 1, 
			text: "Sacrifice: Destroy a mech",
			attack: "2",
			defense: "3",
		},
		{
			name: "Bodyguard Bot",
			type: "Mech", 
			value: 1, 
			text: "If another unit you control would battle, this can take its place",
			attack: "3",
			defense: "3",
		},
		{
			name: "Power Harvester",
			type: "Mech", 
			value: 2, 
			text: "When this destroys a mech, untap a machine",
			attack: "7",
			defense: "9",
		},
		{
			name: "Foreteller",
			type: "Mage", 
			value: 1, 
			text: "Launch: Scry 2",
			attack: "1",
			defense: "4",
		},
		{
			name: "Acolyte Golemancer",
			type: "Mage", 
			value: 1, 
			text: "Launch: Burn 1 scrap. Summon a 2/2 golem.",
			attack: "1",
			defense: "4",
		},
		{
			name: "Arch Golemancer",
			type: "Mage", 
			value: 1, 
			text: "Tap: Burn 1 scrap. Summon a 1/1 golem.",
			attack: 2,
			defense: 4,
		},
		{
			name: "Reality Shifter",
			type: "Mage", 
			value: 1, 
			text: "Launch: Swap a target's attack and defense",
			attack: "1",
			defense: "3",
		},
		{
			name: "Space Hulk",
			type: "Mech", 
			value: 4, 
			text: "Roll. Seek that many cards in your deck.",
			attack: 6,
			defense: 20,
		},
		{
			name: "Sabateur Sorcerer",
			type: "Mage", 
			value: 1, 
			text: "Launch: Your opponent scraps 3.",
			attack: 4,
			defense: 3,
		},
		{
			name: "Necro-engineer",
			type: "Mage Mech", 
			value: 1, 
			attack: "2",
			defense: "4",
		},
		{
			name: "Spiderbot",
			type: "Mech", 
			value: 1, 
			text: "Shutdown: Summon a 1/1 bot.",
			attack: "1",
			defense: "1",
		},
		{
			name: "Anti-mech Alarmist",
			type: "Mage", 
			value: 1, 
			text: "Launch: If you have no mechs in your scrapheap, draw 2 cards.",
			attack: "1",
			defense: "2",
		},
		{
			name: "Overclocked Exterminator",
			type: "Mech", 
			value: 3, 
			text: "Sacrifice a component before attacking",
			attack: 30,
			defense: 10,
		},
		{
			name: "Rusting gargantuan",
			type: "Mech", 
			value: 1, 
			text: "Has -1/-1 for each scrap in your scraphead",
			attack: 10,
			defense: 10,
		},
		{
			name: "Railgun Raptor",
			type: "Mech", 
			value: 2, 
			text: "When this attacks, test X, where X is this unit's attack. Destroy the target unit.",
			attack: 6,
			defense: 9,
		},
		{
			name: "Scrap Golem",
			type: "Mech", 
			value: 1, 
			text: "X is the number of scrap in your scrapheap.",
			attack: "X",
			defense: "X",
		},
		{
			name: "Bomb Bot",
			type: "Mech", 
			value: 1, 
			text: "Shutdown: Deal 3 to a target unit.",
			attack: 1,
			defense: 1,
		},
		{
			name: "Mobile Factory",
			type: "Mech", 
			value: 2, 
			text: "Tap: Scrap 1. Draw a card.",
			attack: 2,
			defense: 7,
		},
		{
			name: "Elissar, Paxfront Tribune",
			type: "Mage", 
			value: 2, 
			text: "Tap: Deal 2 damage to a mech.",
			attack: 7,
			defense: 4,
		},
		{
			name: "Paxfron Emissary",
			type: "Mage", 
			value: 1, 
			text: "Launch: Give a mech +2 attack.",
			attack: 3,
			defense: 4,
		},
		{
			name: "Samsar Repair Drone",
			type: "Mech", 
			value: 1, 
			text: "Launch: Phase in a mech.",
			attack: 2,
			defense: 1,
		},
		{
			name: "Samsar Peace Keeper",
			type: "Mech", 
			value: 1, 
			instant: true,
			text: "Launch: Target doesn't take or deal damage this turn.",
			attack: 1,
			defense: 3,
		},
		{
			name: "Samsar Miracle Worker",
			type: "Mech", 
			value: 1, 
			text: "Tap: Test 5. Draw 1.",
			attack: 1,
			defense: 2,
		},
		{
			name: "Derelict Monocraft",
			type: "Mech", 
			value: 1, 
			text: "When this attacks, fault 1: Destroy this.",
			attack: 6,
			defense: 3,
		},
		{
			name: "Vrak Supply Ship",
			type: "Mech", 
			value: 1, 
			text: "Tap: Draw 2.\n\nWhen this attacks, fault 2: Destroy this.",
			attack: 4,
			defense: 9,
		},
		{
			name: "Imrya",
			type: "Mech", 
			value: 3, 
			text: "Tap: Target mech takes no damage this turn.",
			attack: 3,
			defense: 12,
		},
		{
			name: "Vrak Assault Unit",
			type: "Mech", 
			value: 1, 
			text: "When this attack, fault 4. Destroy this.",
			attack: 5,
			defense: 4,
		},
		{
			name: "Scrap Melder",
			type: "Mage", 
			value: 1, 
			text: "Tap: Pass a test.",
			attack: 2,
			defense: 2,
		},
		{
			name: "Piloted Scout",
			type: "Mech", 
			value: 2, 
			text: "Must use mages as a components instead of mechs.",
			attack: 7,
			defense: 6,
		},
		// {
		// 	name: "",
		// 	type: "Mech", 
		// 	value: 1, 
		// 	text: "",
		// 	attack: ,
		// 	defense: ,
		// },
		// {
		// 	name: "",
		// 	type: "Mech", 
		// 	value: 1, 
		// 	text: "",
		// 	attack: ,
		// 	defense: ,
		// },
		// {
		// 	name: "",
		// 	type: "Mech", 
		// 	value: 1, 
		// 	text: "",
		// 	attack: ,
		// 	defense: ,
		// },
		// {
		// 	name: "",
		// 	type: "Mech", 
		// 	value: 1, 
		// 	text: "",
		// 	attack: ,
		// 	defense: ,
		// },
		// {
		// 	name: "",
		// 	type: "Mech", 
		// 	value: 1, 
		// 	text: "",
		// 	attack: ,
		// 	defense: ,
		// },
		{
			name: "Bombardments",
			type: "Technology",
			text: "Deal 1 damage to all enemies",
		},
		{
			name: "Manifest Flesh",
			type: "Spell",
			upgrade: true,
			text: "This unit is no longer a mech",
			attack: "+1",
			defense: "-1",
		},
		{
			name: "Curse of Steel",
			type: "Spell",
			upgrade: true,
			attack: "-2",
			defense: "-2",
		},
		{
			name: "Drop-pod Mech",
			type: "Mech", 
			instant: true,
			value: 1, 
			text: "Fault 1: Phase this out",
			attack: "4",
			defense: "4",
		},
		{
			name: "Advanced Blueprints",
			type: "Technology",
			text: "Seek a level 3+ mech",
		},
		{
			name: "",
			type: "Factory",  
			text: "Tap: Draw a card, then discard a card.",
		},
		{
			name: "Recycling Center",
			type: "Factory",  
			text: "Tap: Add a card from your scraphead to your deck.",
		},
		{
			name: "Artillery Battery",
			type: "Factory",  
			text: "Tap: Deal 1 damage to target unit.",
		},
		{
			name: "Defense Array",
			type: "Factory",  
			text: "Tap: Prevent 1 damage that would be dealt to target.",
		},
		{
			name: "",
			type: "Factory",  
			text: "",
		},
		{
			name: "",
			type: "Factory",  
			text: "",
		},
	],
};