module.exports = {
	cards: [
		{
			name: "Scrap Hulk",
			type: "Mech", 
			value: 1, 
			text: "**⛢ Launch:** Roll. This has that much health.",
			attack: "3",
			defense: "X",
			rarity: "Common",
		},
		{
			name: "Unstable Laz-Unit",
			type: "Mech", 
			value: 1, 
			text: "Roll at the start of your turn. This has that much attack until your next turn.",
			attack: "X",
			defense: "2",
			rarity: "Rare",
		},
		{
			name: "Smoking Hulk",
			type: "Mech", 
			value: 2, 
			text: "You may burn 1 as a component to summon this",
			attack: "6",
			defense: "6",
			rarity: "Common",
		},
		{
			name: "Prototype",
			type: "Mech", 
			value: 1, 
			text: "When used to summon a mech, this counts as two components",
			attack: "1",
			defense: "1",
			rarity: "Rare",
		},
		{
			name: "Sortek Veteran Defender",
			type: "Mech", 
			value: 2, 
			text: "When used to summon a mech, this counts as two components",
			attack: "10",
			defense: "7",
			rarity: "Rare",
		},
		{
			name: "Warmachine",
			type: "Mech", 
			value: 2, 
			attack: "10",
			defense: "10",
			rarity: "Common",
		},
		{
			name: "Ferromancer",
			type: "Mage", 
			value: 1, 
			text: "Sacrifice: Destroy a mech",
			attack: "2",
			defense: "3",
			rarity: "Common",
		},
		{
			name: "Bodyguard Bot",
			type: "Mech", 
			value: 1, 
			text: "If another unit you control would battle, this can take its place",
			attack: "3",
			defense: "3",
			rarity: "Rare",
		},
		{
			name: "Power Harvester",
			type: "Mech", 
			value: 2, 
			text: "When this destroys a mech, untap a factory",
			attack: "7",
			defense: "9",
			rarity: "Rare",
		},
		{
			name: "Foreteller",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Scry 2",
			attack: "1",
			defense: "4",
			rarity: "Common",
		},
		{
			name: "Acolyte Golemancer",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Burn 1 scrap. Summon a 2/2 golem.",
			attack: "1",
			defense: "4",
			rarity: "Common",
		},
		{
			name: "Arch Golemancer",
			type: "Mage", 
			value: 1, 
			text: "☇ Burn 1 scrap. Summon a 1/1 golem.",
			attack: 2,
			defense: 4,
			rarity: "Rare",
		},
		{
			name: "Reality Shifter",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Swap a target's attack and defense",
			attack: "1",
			defense: "3",
		},
		{
			name: "Space Hulk",
			type: "Mech", 
			value: 4, 
			text: "☇ Roll. Seek that many cards in your deck.",
			attack: 6,
			defense: 20,
			rarity: "Rare",
		},
		{
			name: "Sabateur Sorcerer",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Your opponent scraps 3.",
			attack: 4,
			defense: 3,
			rarity: "Common",
		},
		{
			name: "Necro-engineer",
			type: "Mage Mech", 
			value: 1, 
			attack: "2",
			defense: "4",
			rarity: "Rare",
		},
		{
			name: "Spiderbot",
			type: "Mech", 
			value: 1, 
			text: "**☠ Shutdown:** Summon a 1/1 bot.",
			attack: "1",
			defense: "1",
			rarity: "Common",
		},
		{
			name: "Anti-mech Alarmist",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** If you have no mechs in your scrapheap, draw 2 cards.",
			attack: "1",
			defense: "2",
			rarity: "Rare",
		},
		{
			name: "Overclocked Exterminator",
			type: "Mech", 
			value: 3, 
			text: "Sacrifice a component before attacking",
			attack: 30,
			defense: 10,
			rarity: "Common",
		},
		{
			name: "Rusting gargantuan",
			type: "Mech", 
			value: 1, 
			text: "Has -1/-1 for each scrap in your scrapheap",
			attack: 10,
			defense: 10,
			rarity: "Rare",
		},
		{
			name: "Railgun Raptor",
			type: "Mech", 
			value: 2, 
			text: "When this attacks, test X+, where X is this unit's attack. Destroy the target unit.",
			attack: 6,
			defense: 9,
			rarity: "Rare",
		},
		{
			name: "Scrap Golem",
			type: "Mech", 
			value: 1, 
			text: "X is the number of scrap in your scrapheap.",
			attack: "X",
			defense: "X",
			rarity: "Common",
		},
		{
			name: "Bomb Bot",
			type: "Mech", 
			value: 1, 
			text: "**☠ Shutdown:** Deal 3 to a target unit.",
			attack: 1,
			defense: 1,
			rarity: "Common",
		},
		{
			name: "Mobile Factory",
			type: "Mech", 
			value: 2, 
			text: "☇ Scrap 1. Draw a card.",
			attack: 2,
			defense: 7,
			rarity: "Common",
		},
		{
			name: "Elissar, Paxfront Tribune",
			type: "Mage", 
			value: 2, 
			text: "☇ Deal 2 damage to a mech.",
			attack: 7,
			defense: 4,
			rarity: "Legendary",
		},
		{
			name: "Paxfron Emissary",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Give a mech +2 attack.",
			attack: 3,
			defense: 4,
			rarity: "Common",
		},
		{
			name: "Samsar Repair Drone",
			type: "Mech", 
			value: 1, 
			text: "**⛢ Launch:** Phase in a mech.",
			attack: 2,
			defense: 1,
			rarity: "Common",
		},
		{
			name: "Samsar Peace Keeper",
			type: "Mech", 
			value: 1, 
			instant: true,
			text: "**⛢ Launch:** Target doesn't take or deal damage this turn.",
			attack: 1,
			defense: 3,
			rarity: "Rare",
		},
		{
			name: "Samsar Miracle Worker",
			type: "Mech", 
			value: 1, 
			text: "☇ Test 5. Draw 1.",
			attack: 1,
			defense: 2,
			rarity: "Common",
		},
		{
			name: "Derelict Monocraft",
			type: "Mech", 
			value: 1, 
			text: "When this attacks, **⚠ fault 1**: Destroy this.",
			attack: 6,
			defense: 3,
		},
		{
			name: "Vrak Supply Ship",
			type: "Mech", 
			value: 2, 
			text: "☇ Draw 2.<br/><br/>When this attacks, **⚠ fault 2**: Destroy this.",
			attack: 4,
			defense: 9,
			rarity: "Common",
		},
		{
			name: "Imrya",
			type: "Mech", 
			value: 3, 
			text: "☇ Target mech takes no damage this turn.",
			attack: 3,
			defense: 12,
			rarity: "Legendary",
		},
		{
			name: "Vrak Assault Unit",
			type: "Mech", 
			value: 1, 
			text: "When this attacks, **⚠ fault 4**: Destroy this.",
			attack: 5,
			defense: 4,
			rarity: "Common",
		},
		{
			name: "Evik, Vrak Warlord",
			type: "Mage", 
			value: 1, 
			instant: true,
			text: "**⛢ Launch:**  Seek Scourge, Vrak Warsuit",
			attack: 5,
			defense: 2,
			rarity: "Legendary",
		},
		{
			name: "Scourge, Vrak Warsuit",
			type: "Mech", 
			value: 2, 
			text: "Only **Evik, Vrak Warlord** can be used as a component.<br/><br/>**Armor 1** (If this would take damage, reduce that damage by 1)</br><br/>When this attacks, **⚠ fault 2:** Destroy this.",
			attack: 10,
			defense: 10,
			rarity: "Legendary",
		},
		{
			name: "Scrap Melder",
			type: "Mage", 
			value: 1, 
			text: "☇ Pass a test.",
			attack: 2,
			defense: 2,
			rarity: "Rare",
		},
		{
			name: "Piloted Scout",
			type: "Mech", 
			value: 2, 
			text: "Must use mages as a components instead of mechs.",
			attack: 7,
			defense: 6,
			rarity: "Common",
		},
		{
			name: "Well-Made Mech",
			type: "Mech", 
			value: 1, 
			text: "You can play this from your scrapheap once per turn. It comes into play tapped.",
			attack: 1,
			defense: 1,
			rarity: "Rare",
		},
		{
			name: "Possessed Guardian",
			type: "Mech", 
			value: 1, 
			text: "**☠ Shutdown:** Draw a card.",
			attack: 2,
			defense: 3,
			rarity: "Common",
		},
		{
			name: "Piloted Mechsuit",
			type: "Mech", 
			value: 2, 
			text: "⚙ Requires a mage as a component",
			attack: 8,
			defense: 10,
			rarity: "Common",
		},
		{
			name: "Squadron Leader",
			type: "Mech", 
			value: 3, 
			text: "⚙ Requires a mech and a mage as components",
			attack: 12,
			defense: 15,
			rarity: "Common",
		},
		{
			name: "Fuel-Hungry Hulk",
			type: "Mech", 
			value: 2, 
			text: "If this is targeted by an effect, you may burn 3 to negate that effect.",
			attack: 10,
			defense: 8,
			rarity: "Rare",
		},
		{
			name: "Malfunctionist",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Destroy target level 1 mech.",
			attack: 3,
			defense: 1,
			rarity: "Common",
		},
		{
			name: "Heavy Vrak Carrack",
			type: "Mech", 
			value: 2, 
			text: "Damage dealt to this by level 1 mechs is ignored.<br/><br/>When attacking, fault 1: Destory this",
			attack: 8,
			defense: 13,
			rarity: "Rare",
		},
		{
			name: "Wisp",
			type: "Spirit", 
			value: 1, 
			instant: true,
			text: "This can be used instead of a mage component.<br/><br/>**☠ Shutdown:** Draw a card.",
			attack: 0,
			defense: 1,
			rarity: "Rare",
		},
		{
			name: "Wisp Willer",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Target a mech. Test X, where X is the target unit's level. Take control of the target.",
			attack: 1,
			defense: 1,
			rarity: "Rare",
		},
		{
			name: "Bombardment",
			type: "Action",
			text: "Deal 1 damage to all enemies",
			rarity: "Common",
		},
		{
			name: "Manifest Flesh",
			type: "Spell",
			upgrade: true,
			text: "This unit is no longer a mech",
			attack: "+1",
			defense: "-1",
			rarity: "Rare",
		},
		{
			name: "Curse of Steel",
			type: "Spell",
			upgrade: true,
			attack: "-2",
			defense: "-2",
			rarity: "Common",
		},
		{
			name: "Drop-Pod Titan",
			type: "Mech", 
			instant: true,
			value: 1, 
			text: "When this untaps, **⚠ Fault 1:** Phase this out",
			attack: "5",
			defense: "5",
			rarity: "Common",
		},
		{
			name: "Advanced Blueprints",
			type: "Technology",
			text: "Seek a level 3+ mech",
			rarity: "Rare",
		},
		{
			name: "♽ Recycling Center",
			type: "Factory",  
			text: "☇ Discard a card, then draw a card.",
			rarity: "Common",
		},
		{
			name: "Repair Shop",
			type: "Factory",  
			text: "☇ Add a card from your scrapheap to your deck.",
			rarity: "Common",
		},
		{
			name: "Artillery Battery",
			type: "Factory",  
			text: "☇ Deal 1 damage to target unit.",
			rarity: "Common",
		},
		{
			name: "Defense Array",
			type: "Factory",  
			text: "☇ Prevent 1 damage that would be dealt to target.",
			rarity: "Common",
		},
		{
			name: "Repair Line",
			type: "Factory",  
			text: "☇ Shuffle a scrap into your deck.",
			rarity: "Common",
		},
		{
			name: "Faulty Assembly Line",
			type: "Factory",  
			text: "☇ Scrap 1.",
			rarity: "Rare",
		},
		{
			name: "Trick of the Eye",
			type: "Spell",  
			instant: true,
			text: "Reroll 1 dice rolled.",
			rarity: "Rare",
		},
		{
			name: "Search Through Junk",
			type: "Action",  
			text: "Roll. Draw that many cards. Discard until you have three cards.",
			rarity: "Common",
		},
		{
			name: "Missile Barrage",
			type: "Action",  
			text: "Roll 4. Deal 2 damage for each 4+ rolled.", //1
			rarity: "Common",
		},
		{
			name: "The Claw",
			type: "Technology",  
			text: "Test 5+: Seek a card.",
			rarity: "Rare",
		},
		{
			name: "Harvest Scrap",
			type: "Action",  
			text: "Shuffle the top three cards of your scrapheap into your deck",
			rarity: "Common",
		},
		{
			name: "Overclock",
			type: "Technology",  
			instant: true,
			text: "Untap a mech",
		},
		{
			name: "Powercut",
			type: "Technology",  
			instant: true,
			text: "Tap a factory",
			rarity: "Common",
		},
		{
			name: "EMP",
			type: "Technology",
			instant: true,
			text: "Tap all factories",
			rarity: "Rare",
		},
		{
			name: "Patent Lawsuit",
			type: "Action",  
			text: "Burn a card in your scrapheap. Destroy a mech or factory with the same name.",
			rarity: "Rare",
		},
		{
			name: "Strike!",
			type: "Action",  
			instant: true,
			text: "Tap a factory. It doesn't untap next reboot phase.",
			rarity: "Common",
		},
		{
			name: "Recycle",
			type: "Action",  
			text: "Burn 6. Draw 3.",
			rarity: "Common",
		},
		{
			name: "Assembly Line",
			type: "Factory",  
			text: "☇ Burn 1. Summon a 1/1 mech.",
			rarity: "Common",
		},
		{
			name: "Hex",
			type: "Spell",  
			text: "Roll 6. If you get a 1, your opponent discards a card.",
			rarity: "Rare",
		},
		{
			name: "Self-Destruct Sequence",
			type: "Action",  
			text: "Sacrifice a mech. Deal damage equal to its health to all enemies.",
			rarity: "Rare",
		},
		{
			name: "Disassemble",
			type: "Action",  
			text: "Destroy a level 2+ mech you control. Its component remain.<br/><br/>Draw a card.",
			rarity: "Common",
		},
		{
			name: "Reboot Systems",
			type: "Action",  
			text: "Discard your hand. Draw 4 cards.",
			rarity: "Common",
		},
		{
			name: "Starbind",
			type: "Spell",  
			text: "Phase out 1 target unit (flip it over)",
			rarity: "Rare",
		},
		{
			name: "Hack",
			type: "Action",  
			text: "Phase out target mech",
			rarity: "Common",
		},
		{
			name: "Ghost in the Machine",
			type: "",  
			text: "Not sure",
			rarity: "Rare",
		},
		{
			name: "AI Unit",
			type: "Technology",  
			text: "You can use this as a substitute for a mage component. The summoned unit has 'Test 2+ to attack'",
			rarity: "Rare",
		},
		{
			name: "Mech Manufacture",
			type: "Factory",  
			text: "☇ Summon a 1/1 mech.",
			rarity: "Common",
		},
		{
			name: "Sortek Defense Field",
			type: "Factory",  
			text: "☇ Prevent all damage that would be dealt to target factory this turn.", // if other target factory would be destroyed this turn, it isn't
			rarity: "Rare",
		},
		{
			name: "Ambush",
			type: "Action",  
			instant: true,
			text: "Target a mech you control and another mech. The two units fight.",
			rarity: "Common",
		},
		{
			name: "False Intelligence",
			type: "Action",  
			instant: true,
			text: "When an enemy attacks, choose a new target you control.",
			rarity: "Common",
		},
		{
			name: "Reload",
			type: "Action",  
			instant: true,
			text: "Draw 2 cards",
			rarity: "Common",
		},
		{
			name: "Intone Amar",
			type: "Spell",  
			text: "Test 3+: The next mech you summon requires 1 less component.",
			rarity: "Rare",
		},
		{
			name: "New Parliament",
			type: "Event",  
			text: "Destroy all events",
			rarity: "Rare",
		},
		{
			name: "Glitch",
			type: "Action",  
			instant: true,
			text: "Discard a card. <br/><br/>Your opponent cannot use mechs as components this turn.",
			rarity: "Common",
		},
		{
			name: "Forge Parts",
			type: "Action", 
			instant: true, 
			text: "Shuffle the top scrap into your deck. Draw a card.",
			rarity: "Common",
		},
		{
			name: "Infernal Binding",
			type: "Spell",  
			instant: true,
			text: "Sacrifice a mech. Destroy target mech.",
			rarity: "Common",
		},
		{
			name: "Means of Production",
			type: "Action",  
			text: "Seek a factory",
			rarity: "Rare",
		},
		{
			name: "Harvest Parts",
			type: "Action",  
			text: "Burn 1. Phase in a mech.",
			rarity: "Rare",
		},
		{
			name: "Scrap for Parts",
			type: "Action",  
			text: "Sacrifice a mech. Return a factory from your scrapheap into play.",
			rarity: "Common",
		},
		{
			name: "Verdence",
			type: "Spell",  
			text: "Draw 2 cards",
			rarity: "Common",
		},
		{
			name: "Decay",
			type: "Spell",  
			text: "Roll. Target player scraps X, where X is the result.",
			rarity: "Common",
		},
		{
			name: "Overtime",
			type: "Event",  
			//faction: "⚙"
			//faction: "⚛"
			//faction: "⚕"
			//faction: "☼"
			//faction: "☯"
			text: "Untap your factories",
			rarity: "Common",
		},
		{
			name: "Layline Gate",
			type: "Factory",  
			text: "☇ Draw a card. Discard a card.",
			rarity: "Rare",
		},
		{
			name: "Guerilla Warfare",
			type: "Action",  
			text: "Phase our your units until your next reboot phase",
			rarity: "Rare",
		},
		{
			name: "Lunar Blessing",
			upgrade: true,
			type: "Spell",  
			//faction: "✇"
			text: "**☠ Shutdown:** Return this unit to your hand.",
			rarity: "Rare",
		},
		{
			name: "Wild Overgrowth",
			type: "Spell",
			instant: true,  
			text: "Tap target enemy unit",
			rarity: "Common",
		},
		{
			name: "✇ Invoker Layline",
			type: "Factory",  
			text: "☇ Test 6+: Destroy target creature.",
			rarity: "Legendary",
		},
		{
			name: "Shield",
			upgrade: true,  
			text: "Draw a card.<br/>If this unit would take damage, prevent it and scrap this.",
		},
		{
			name: "Battery",
			upgrade: true,  
			text: "After an attack, destory this.",
			rarity: "Common",
		},
		{
			name: "Rust",
			upgrade: true,  
			text: "This can only upgrade mechs",
			attack: "-3",
			defense: "-3",
			rarity: "Common",
		},
		{
			name: "Extra Arm",
			upgrade: true,  
			attack: "+2",
			rarity: "Common",
		},
		{
			name: "Ejector Seat",
			upgrade: true,  
			text: "**☠ Shutdown:** This unit's components remain on the battlefield.",
			rarity: "Common",
		},
		{
			name: "Icarus Suit",
			upgrade: true,  
			text: "Can only upgrade mages.<br/>This unit counts as a mech.",
			attack: "+2",
			defense: "+2",
			rarity: "Common",
		},
		{
			name: "Machine Rot",
			type: "Spell",
			upgrade: true,  
			text: "Can ony upgrade mechs",
			attack: "-1",
			defense: "-3",
			rarity: "Common",
		},
		{
			name: "Vrak Augments",
			upgrade: true,  
			text: "When this attacks, **⚠ fault 1**: Scrap this.",
			attack: "+6",
			defense: "+1",
			rarity: "Common",
		},
		{
			name: "Scrapbind",
			type: "Spell",
			upgrade: true,  
			text: "X = number of cards in this unit's scrapheap.",
			attack: "-X",
			rarity: "Rare",
		},
		{
			name: "Climbing Vines",
			type: "Spell",
			upgrade: true,  
			attack: "-4",
			rarity: "Common",
		},
		{
			name: "Exoskeleton",
			upgrade: true,  
			text: "Can only upgrade a mage.<br/>Unit counts as a mech.",
			attack: "+3",
			defense: "+3",
			rarity: "Common",
		},
		{
			name: "Pact of Knowledge",
			type: "Spell",
			text: "Destroy a mage you control. Seek a spell.",
			rarity: "Rare",
		},
		{
			name: "Veto",
			type: "Action",
			instant: true,
			text: "Negate target action or event",
			rarity: "Common",
		},
		{
			name: "Recharge",
			type: "Action",  
			instant: true,
			text: "Untap target mech.",
			rarity: "Common",
		},
		{
			name: "Second Term",
			type: "Event",  
			text: "After you play an action, exile it. After 2 actions are exiled this way, discard this card to return those actions to your hand.",
			rarity: "Rare",
		},
		{
			name: "Emergency Shutdown",
			type: "Action",  
			text: "Destroy target mech you control. Draw a card.",
			rarity: "Rare",
		},
		{
			name: "Standby",
			type: "Action",  
			instant: true,
			text: "Phase out target mech you control.",
			rarity: "Common",
		},
		{
			name: "Spider Mines",
			type: "Technology",  
			text: "Play this card face down. When your opponent plays their next unit, activate this to deal 5 damage to that target.",
			rarity: "Rare",
		},
		{
			name: "Satellite Strike",
			type: "Action",  
			text: "Choose one:</br>➢ Deal 3 damage to target unit.</br>➢ Destroy target factory.",
			rarity: "Common",
		},
		{
			name: "Evasive Manouvres",
			type: "Action",  
			instant: true,
			text: "Return target unit you control to your hand.",
			rarity: "Common",
		},
		{
			name: "Drop-Pod",
			type: "Technology",  
			text: "Summon a level 1 unit from your hand. Launch effects aren't activated.",
			rarity: "Common",
		},
		{
			name: "Action Stations",
			type: "Action",  
			text: "Seek an action card",
			rarity: "Common",
		},
		{
			name: "Restart",
			type: "Action",  
			text: "Shuffle your hand into your deck. Draw that many cards.",
			rarity: "Common",
		},
		{
			name: "Cleanup",
			type: "Action",  
			text: "Shuffle 5 scrap into your deck. Draw a card.",
			rarity: "Common",
		},
		{
			name: "Siphon Energy",
			type: "Action",  
			text: "Destroy target mech you control. Draw 3 cards.",
			rarity: "Common",
		},
		{
			name: "Trade War",
			type: "Action",  
			text: "You may destroy target factories you control. You opponent destroys a factory for each you destroy this way.",
			rarity: "Rare",
		},
		{
			name: "Mobilize from the Void",
			type: "Spell",  
			text: "Draw a card. If it's a mech, summon it phased out.",
			rarity: "Common",
		},
		{
			name: "Arcane Resonance",
			type: "Spell",  
			text: "Draw a card. If it’s a mage, summon it. Any Launch abilities don’t ativate.",
			rarity: "Common",
		},
		{
			name: "Power Surge",
			type: "Action",  
			text: "Deal damage equal to the number of mechs you have to target enemy",
			rarity: "Common",
		},
		{
			name: "Rift Javelin",
			type: "Technology",  
			text: "Deal 2 damage. Shuffle this into card your deck.",
			rarity: "Rare",
		},
		{
			name: "Flesh from Iron",
			type: "Spell",
			instant: true,  
			text: "Target mech becomes a mage",
			rarity: "Rare",
		},
		{
			name: "Needle in a Haystack",
			type: "Action",
			instant: true,  
			text: "Name a card. Reveal the top card of your deck. If the card revealed has this name, draw it and repeat this effect.",
			rarity: "Rare",
		},
		{
			name: "There's life in that yet!",
			type: "Action",
			instant: true,  
			text: "Put a card from your scrapheap onto the top of your deck.",
			rarity: "Rare",
		},
		{
			name: "Zenithar Ranger",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Deal 2 damage to target.",
			attack: "4",
			defense: "2",
			rarity: "Common",
		},
		{
			name: "Zenithar Assassain",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Look at your opponents hand. Choose one card to discard.",
			attack: "2",
			defense: "1",
			rarity: "Rare",
		},
		{
			name: "Sortek Artillery Unit",
			type: "Mech", 
			value: 1, 
			text: "**⛢ Launch:** Deal 4 damage to target.",
			attack: "2",
			defense: "2",
			rarity: "Common",
		},
		{
			name: "Zenithar Striker",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Destroy target factory.",
			attack: "1",
			defense: "4",
			rarity: "Common",
		},
		{
			name: "Scrap Scultor",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Target mech. Burn cards equal to its health to summon a copy.",
			attack: "1",
			defense: "2",
			rarity: "Common",
		},
		{
			name: "Peaceful Pacifier",
			type: "Mech", 
			value: 1, 
			instant: true,
			text: "**⛢ Launch:** Tap target unit.",
			attack: "1",
			defense: "5",
			rarity: "Common",
		},
		{
			name: "Zenithar Sapper",
			type: "Mage", 
			value: 1, 
			instant: true,
			text: "**⛢ Launch:** Tap target attacking mech. Draw a card.",
			attack: "2",
			defense: "3",
			rarity: "Common",
		},
		{
			name: "Strike Leader",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Seek a unit named **Zenithar Striker**",
			attack: "2",
			defense: "2",
			rarity: "Rare",
		},
		{
			name: "Methil, Harbringer",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Seek an event called **Planetary Invasion**.",
			attack: "3",
			defense: "1",
			rarity: "Legendary",
		},
		{
			name: "Samsar Missionary",
			type: "Mech", 
			value: 2, 
			text: "☇ Tap target unit.",
			attack: "4",
			defense: "8",
			rarity: "Common",
		},
		{
			name: "Vrak Subjegator",
			type: "Mech", 
			value: 1, 
			text: "☇ Tap target mech.",
			attack: "3",
			defense: "3",
			rarity: "Common",
		},
		{
			name: "Grappling Sapper",
			type: "Mech", 
			value: 2, 
			text: "☇ Tap target unit.",
			attack: "4",
			defense: "6",
			rarity: "Common",
		},
		{
			name: "Sortek Standard Bearer",
			type: "Mage", 
			value: 1, 
			text: "After this attacks, if your opponent controls more units than you, draw a card.",
			attack: "3",
			defense: "4",
			rarity: "Common",
		},
		{
			name: "Recovery Drone",
			type: "Mech", 
			value: 1, 
			text: "☇ Return a mech with toughness 2 or less from your scraphead to the battlefield.",
			attack: "2",
			defense: "4",
			rarity: "Common",
		},
		{
			name: "Static Striker",
			type: "Mage", 
			value: 1, 
			text: "This has +1/+1 for each other friendly mech.",
			attack: "2",
			defense: "3",
			rarity: "Common",
		},
		{
			name: "Sortek Civil Unit",
			type: "Mech", 
			value: 1, 
			text: "**☠ Shutdown:** Summon a 1/1 mage.",
			attack: "3",
			defense: "4",
			rarity: "Common",
		},
		{
			name: "Scrap Thief",
			type: "Mage", 
			value: 1, 
			text: "Whenever this deals damage to the opponent, draw a card.",
			attack: "4",
			defense: "2",
			rarity: "Common",
		},
		{
			name: "Mech Scavenger",
			type: "Mech", 
			value: 2, 
			text: "Whenever this destroys a mech, give this +1/+1.",
			attack: "3",
			defense: "10",
			rarity: "Common",
		},
		{
			name: "Amika, Changer of Lumaro",
			type: "Mage", 
			value: 1, 
			text: "☇ Burn. Scry. Scrap. Draw",
			attack: "3",
			defense: "6",
			rarity: "Common",
		},
		{
			name: "Lumaro Protector",
			type: "Mage", 
			value: 1, 
			text: "If this would take damage, you may burn that many cards instead.",
			attack: "2",
			defense: "4",
			rarity: "Rare",
		},
		{
			name: "Vrak Armoured Carrier",
			type: "Mech", 
			value: 2, 
			text: "**☠ Shutdown:** Summon a lower level mech from your scrapheap.",
			attack: "10",
			defense: "6",
			rarity: "Common",
		},
		{
			name: "Vrak Mobile Hangar",
			type: "Mech", 
			value: 3, 
			text: "**☠ Shutdown:** Summon a lower level mech from your scrapheap.",
			attack: "15",
			defense: "12",
			rarity: "Common",
		},
		{
			name: "Vrak Smoke Caller",
			type: "Mage", 
			value: 1, 
			text: "**⛢ Launch:** Add target unit from burned pile onto the top of your deck.",
			attack: "1",
			defense: "2",
			rarity: "Rare",
		},
		{
			name: "Barat, Smoke Whisper",
			type: "Mage", 
			value: 1, 
			text: "Whenever you burn a card, summon a X/X smoke elemental with stats equal to the number of cards burned.",
			attack: "4",
			defense: "4",
			rarity: "Legendary",
		},
		{
			name: "Zenithar Offworlder",
			type: "Mech", 
			value: 1, 
			text: "**Boosters 3:** Burn 3 cards to become unblockable this turn.",
			attack: "3",
			defense: "3",
			rarity: "Common",
		},
		{
			name: "Steelbound Arcanist",
			type: "Mech", 
			value: 1, 
			text: "**⛢ Launch:** Burn 2.",
			attack: "5",
			defense: "6",
			rarity: "Common",
		},
		{
			name: "Armor Plating",
			upgrade: true,  
			text: "**Armor 1** (If this would take damage, reduce that damage by 1)",
		},
		{
			name: "Steel Reinforcements",
			upgrade: true,  
			text: "Draw a card",
			defense: "+3",
		},
		{
			name: "Planetary Invasion",
			type: "Event",  
			text: "Until the end of your turn, each time you summon a mech, draw a card",
		},
		{
			name: "Bono, Hexsuit",
			type: "Mech", 
			value: 1, 
			text: "**⛢ Launch:** Deal 5 damage to target unit.",
			attack: "2",
			defense: "6",
			rarity: "Legendary",
		},
		{
			name: "Mal, Paxfront Chosen",
			type: "Mage", 
			value: 1, 
			text: "When this takes damage, seek **Bono, Ancient Armor**.",
			attack: "2",
			defense: "4",
			rarity: "Legendary",
		},
		{
			name: "Malbono, Monstrosity",
			type: "Mech", 
			value: 2, 
			text: "Must use units named Mal and Bono as components.<br/><br/>**⛢ Launch:** Deal 5 damage to all other units.<br/><br/>Forcefield: Tap a mech to attack this.",
			attack: "5",
			defense: "10",
			rarity: "Legendary",
		},
		{
			name: "Unstable Powercore",
			type: "Technology",
			upgrade: true,
			text: "**☠ Shutdown:** Deal damage equal to this unit's attack to its owner.",
			attack: "+1",
			rarity: "Rare",
		},
		{
			name: "Precision Strike",
			type: "Technology",
			text: "Destroy target factory.",
			rarity: "Common",
		},
		{
			name: "Emergency Machinery",
			type: "Factory",
			text: "☇ This becomes 3/3 mech until the end of turn.<br/><br/>☇ Shuffle 1 scrap into your deck.",
			rarity: "Rare",
		},
	],
};

// ❖
// ⚀
// ⚁
// ⚂
// ⚃
// ⚄
// ⚅
// ♾