module.exports = {
	cards: [
		{
			name: "Scrap Hulk",
			type: "Mech", 
			value: 1, 
			text: "⛢ Launch: Roll. This has that much health.",
			attack: "3",
			defense: "*",
		},
		{
			name: "Unstable Laz-Unit",
			type: "Mech", 
			value: 1, 
			text: "Roll at the start of your turn. This has that much attack until your next turn.",
			attack: "*",
			defense: "2",
		},
		{
			name: "Smoking Hulk",
			type: "Mech", 
			value: 2, 
			text: "You may burn 1 as a component to summon this",
			attack: "6",
			defense: "6",
		},
		{
			name: "Prototype",
			type: "Mech", 
			value: 1, 
			text: "When used to summon a mech, this counts as two components",
			attack: "1",
			defense: "1",
		},
		{
			name: "Warmachine",
			type: "Mech", 
			value: 2, 
			attack: "10",
			defense: "10",
		},
		{
			name: "Ferromancer",
			type: "Mage", 
			value: 1, 
			text: "Sacrifice: Destroy a mech",
			attack: "2",
			defense: "3",
		},
		{
			name: "Bodyguard Bot",
			type: "Mech", 
			value: 1, 
			text: "If another unit you control would battle, this can take its place",
			attack: "3",
			defense: "3",
		},
		{
			name: "Power Harvester",
			type: "Mech", 
			value: 2, 
			text: "When this destroys a mech, untap a machine",
			attack: "7",
			defense: "9",
		},
		{
			name: "Foreteller",
			type: "Mage", 
			value: 1, 
			text: "⛢ Launch: Scry 2",
			attack: "1",
			defense: "4",
		},
		{
			name: "Acolyte Golemancer",
			type: "Mage", 
			value: 1, 
			text: "⛢ Launch: Burn 1 scrap. Summon a 2/2 golem.",
			attack: "1",
			defense: "4",
		},
		{
			name: "Arch Golemancer",
			type: "Mage", 
			value: 1, 
			text: "☇ Burn 1 scrap. Summon a 1/1 golem.",
			attack: 2,
			defense: 4,
		},
		{
			name: "Reality Shifter",
			type: "Mage", 
			value: 1, 
			text: "⛢ Launch: Swap a target's attack and defense",
			attack: "1",
			defense: "3",
		},
		{
			name: "Space Hulk",
			type: "Mech", 
			value: 4, 
			text: "Roll. Seek that many cards in your deck.",
			attack: 6,
			defense: 20,
		},
		{
			name: "Sabateur Sorcerer",
			type: "Mage", 
			value: 1, 
			text: "⛢ Launch: Your opponent scraps 3.",
			attack: 4,
			defense: 3,
		},
		{
			name: "Necro-engineer",
			type: "Mage Mech", 
			value: 1, 
			attack: "2",
			defense: "4",
		},
		{
			name: "Spiderbot",
			type: "Mech", 
			value: 1, 
			text: "☠ Shutdown: Summon a 1/1 bot.",
			attack: "1",
			defense: "1",
		},
		{
			name: "Anti-mech Alarmist",
			type: "Mage", 
			value: 1, 
			text: "⛢ Launch: If you have no mechs in your scrapheap, draw 2 cards.",
			attack: "1",
			defense: "2",
		},
		{
			name: "Overclocked Exterminator",
			type: "Mech", 
			value: 3, 
			text: "Sacrifice a component before attacking",
			attack: 30,
			defense: 10,
		},
		{
			name: "Rusting gargantuan",
			type: "Mech", 
			value: 1, 
			text: "Has -1/-1 for each scrap in your scraphead",
			attack: 10,
			defense: 10,
		},
		{
			name: "Railgun Raptor",
			type: "Mech", 
			value: 2, 
			text: "When this attacks, test X, where X is this unit's attack. Destroy the target unit.",
			attack: 6,
			defense: 9,
		},
		{
			name: "Scrap Golem",
			type: "Mech", 
			value: 1, 
			text: "X is the number of scrap in your scrapheap.",
			attack: "X",
			defense: "X",
		},
		{
			name: "Bomb Bot",
			type: "Mech", 
			value: 1, 
			text: "☠ Shutdown: Deal 3 to a target unit.",
			attack: 1,
			defense: 1,
		},
		{
			name: "Mobile Factory",
			type: "Mech", 
			value: 2, 
			text: "☇ Scrap 1. Draw a card.",
			attack: 2,
			defense: 7,
		},
		{
			name: "Elissar, Paxfront Tribune",
			type: "Mage", 
			value: 2, 
			text: "☇ Deal 2 damage to a mech.",
			attack: 7,
			defense: 4,
		},
		{
			name: "Paxfron Emissary",
			type: "Mage", 
			value: 1, 
			text: "⛢ Launch: Give a mech +2 attack.",
			attack: 3,
			defense: 4,
		},
		{
			name: "Samsar Repair Drone",
			type: "Mech", 
			value: 1, 
			text: "⛢ Launch: Phase in a mech.",
			attack: 2,
			defense: 1,
		},
		{
			name: "Samsar Peace Keeper",
			type: "Mech", 
			value: 1, 
			instant: true,
			text: "⛢ Launch: Target doesn't take or deal damage this turn.",
			attack: 1,
			defense: 3,
		},
		{
			name: "Samsar Miracle Worker",
			type: "Mech", 
			value: 1, 
			text: "☇ Test 5. Draw 1.",
			attack: 1,
			defense: 2,
		},
		{
			name: "Derelict Monocraft",
			type: "Mech", 
			value: 1, 
			text: "When this attacks, ⚠ fault 1: Destroy this.",
			attack: 6,
			defense: 3,
		},
		{
			name: "Vrak Supply Ship",
			type: "Mech", 
			value: 1, 
			text: "☇ Draw 2.\n\nWhen this attacks, ⚠ fault 2: Destroy this.",
			attack: 4,
			defense: 9,
		},
		{
			name: "Imrya",
			type: "Mech", 
			value: 3, 
			text: "☇ Target mech takes no damage this turn.",
			attack: 3,
			defense: 12,
		},
		{
			name: "Vrak Assault Unit",
			type: "Mech", 
			value: 1, 
			text: "When this attack, ⚠ fault 4. Destroy this.",
			attack: 5,
			defense: 4,
		},
		{
			name: "Scrap Melder",
			type: "Mage", 
			value: 1, 
			text: "☇ Pass a test.",
			attack: 2,
			defense: 2,
		},
		{
			name: "Piloted Scout",
			type: "Mech", 
			value: 2, 
			text: "Must use mages as a components instead of mechs.",
			attack: 7,
			defense: 6,
		},
		{
			name: "Well-Made Mech",
			type: "Mech", 
			value: 1, 
			text: "You can play this from your scraphead once per turn. It comes into play tapped.",
			attack: 1,
			defense: 1,
		},
		{
			name: "Possessed Guardian",
			type: "Mech", 
			value: 1, 
			text: "☠ Shutdown: Draw a card.",
			attack: 2,
			defense: 3,
		},
		{
			name: "Piloted Mechsuit",
			type: "Mech", 
			value: 2, 
			text: "⚙ Requires a mage as a component",
			attack: 8,
			defense: 10,
		},
		{
			name: "Squadron Leader",
			type: "Mech", 
			value: 3, 
			text: "⚙ Requires a mech and a mage as components",
			attack: 12,
			defense: 15,
		},
		{
			name: "Wisp",
			type: "Spirit", 
			value: 1, 
			instant: true,
			text: "This can be used instead of a mage component.\n☠ Shutdown: Draw a card.",
			attack: 0,
			defense: 1,
		},
		{
			name: "Wisp Willer",
			type: "Mage", 
			value: 1, 
			text: "⛢ Launch: Target a mech. Test X, where X is the target unit's level. Take control of the target.",
			attack: 1,
			defense: 1,
		},
		{
			name: "Bombardment",
			type: "Action",
			text: "Deal 1 damage to all enemies",
		},
		{
			name: "Manifest Flesh",
			type: "Spell",
			upgrade: true,
			text: "This unit is no longer a mech",
			attack: "+1",
			defense: "-1",
		},
		{
			name: "Curse of Steel",
			type: "Spell",
			upgrade: true,
			attack: "-2",
			defense: "-2",
		},
		{
			name: "Drop-Pod Mech",
			type: "Mech", 
			instant: true,
			value: 1, 
			text: "⚠ Fault 1: Phase this out",
			attack: "4",
			defense: "4",
		},
		{
			name: "Advanced Blueprints",
			type: "Technology",
			text: "Seek a level 3+ mech",
		},
		{
			name: "",
			type: "Factory",  
			text: "☇ Draw a card, then discard a card.",
		},
		{
			name: "Recycling Center",
			type: "Factory",  
			text: "☇ Add a card from your scraphead to your deck.",
		},
		{
			name: "Artillery Battery",
			type: "Factory",  
			text: "☇ Deal 1 damage to target unit.",
		},
		{
			name: "Defense Array",
			type: "Factory",  
			text: "☇ Prevent 1 damage that would be dealt to target.",
		},
		{
			name: "Repair Line",
			type: "Factory",  
			text: "☇ Shuffle a scrap into your deck.",
		},
		{
			name: "Faulty Assembly Line",
			type: "Factory",  
			text: "☇ Scrap 1.",
		},
		{
			name: "Trick of the Eye",
			type: "Spell",  
			text: "Reroll 1 dice rolled for a Test or Fault.",
		},
		{
			name: "Search Through Junk",
			type: "Action",  
			text: "Roll. Draw that many. Discard until you have three cards.",
		},
		{
			name: "Missile Barrage",
			type: "",  
			text: "Roll 4. Deal 1 damage for each 4+ rolled.",
		},
		{
			name: "The Claw",
			type: "Technology",  
			text: "Test 5+: Seek a card.",
		},
		{
			name: "Harvest Scrap",
			type: "Action",  
			text: "Shuffle the top three cards of your scraphead into your deck",
		},
		{
			name: "Overclock",
			type: "Technology",  
			instant: true,
			text: "Untap a mech",
		},
		{
			name: "Powercut",
			type: "Technology",  
			instant: true,
			text: "Tap a factory",
		},
		{
			name: "EMP",
			type: "Technology",
			text: "Tap all factories",
		},
		{
			name: "Patent Lawsuit",
			type: "Action",  
			text: "Burn a card in your scrapheap. Destroy a mech or factory with the same name.",
		},
		{
			name: "Strike!",
			type: "Action",  
			instant: true,
			text: "Tap a factory. It doesn't untap next reboot phase.",
		},
		{
			name: "Recycle",
			type: "Action",  
			text: "Burn 3. Draw 1.",
		},
		{
			name: "Assembly Line",
			type: "Factory",  
			text: "☇ Burn 1. Summon a 1/1 mech.",
		},
		{
			name: "Hex",
			type: "Spell",  
			text: "Roll 6. If you get a 1, your opponent discards a card.",
		},
		{
			name: "Self-Destruct Sequence",
			type: "Action",  
			text: "Sacrifice a mech. Deal damage equal to its health to all enemies.",
		},
		{
			name: "Disassemble",
			type: "Action",  
			text: "Destroy a level 2+ mech you control. Its component remain. Draw a card.",
		},
		{
			name: "Reboot Systems",
			type: "Action",  
			text: "Discard your hand. Draw 4 cards.",
		},
		{
			name: "Starbind",
			type: "Spell",  
			text: "Phase out 1 target unit (flip it over)",
		},
		{
			name: "Hack",
			type: "Action",  
			text: "Phase out target mech",
		},
		{
			name: "Ghost in the Machine",
			type: "",  
			text: "Not sure",
		},
		{
			name: "AI Unit",
			type: "Technology",  
			text: "You can use this as a substitute for a mage component. The summoned unit has 'Test 2+ to attack'",
		},
		{
			name: "Mech Manufacture",
			type: "Factory",  
			text: "☇ Summon a 1/1 mech.",
		},
		{
			name: "Sortek Defense Field",
			type: "Factory",  
			text: "☇ Prevent all damage that would be dealt to target factory this turn.",
		},
		{
			name: "Ambush",
			type: "Action",  
			instant: true,
			text: "Target a mech you control and another mech. The two units fight.",
		},
		{
			name: "False Intelligence",
			type: "Action",  
			instant: true,
			text: "When an enemy attacks, choose a new target you control.",
		},
		{
			name: "Reload",
			type: "Action",  
			instant: true,
			text: "Draw 2 cards",
		},
		{
			name: "Intone Amar",
			type: "Spell",  
			text: "Test 3+: The next mech you summon requires 1 less component.",
		},
		{
			name: "New Parliament",
			type: "Event",  
			text: "Destroy an event",
		},
		{
			name: "Glitch",
			type: "Action",  
			instant: true,
			text: "Discard a card. Your opponent cannot use mechs as components this turn.",
		},
		{
			name: "Forge Parts",
			type: "Action", 
			instant: true, 
			text: "Shuffle the top scrap into your deck. Draw a card.",
		},
		{
			name: "Infernal Binding",
			type: "Spell",  
			instant: true,
			text: "Sacrifice a mech. Destroy target mech.",
		},
		{
			name: "Means of Production",
			type: "Action",  
			text: "Seek a factory",
		},
		{
			name: "Harvest Parts",
			type: "Action",  
			text: "Burn 1. Phase in a mech.",
		},
		{
			name: "Scrap for Parts",
			type: "Action",  
			text: "Sacrifice a mech. Return a factory from your scraphead into play.",
		},
		{
			name: "Verdence",
			type: "Spell",  
			text: "Draw 2 cards",
		},
		{
			name: "Decay",
			type: "Spell",  
			text: "Roll. Target player scraps X, where X is the result.",
		},
		{
			name: "Overtime",
			type: "Event",  
			//faction: "⚙"
			//faction: "⚛"
			//faction: "⚕"
			//faction: "☼"
			//faction: "☯"
			text: "Untap your factories",
		},
		{
			name: "Layline Gate",
			type: "Factory",  
			text: "☇ Draw a card. Discard a card.",
		},
		{
			name: "Guerilla Warfare",
			type: "Action",  
			text: "Phase our your units until your next reboot phase",
		},
		{
			name: "Lunar Blessing",
			upgrade: true,
			type: "Spell",  
			//faction: "✇"
			text: "☠ Shutdown: Return this unit to your hand.",
		},
		{
			name: "Wild Overgrowth",
			type: "Spell",
			instant: true,  
			text: "Tap target enemy unit",
		},
		{
			name: "✇ Invoker Layline",
			type: "Factory",  
			text: "☇ Test 6+: Destroy target creature.",
		},
	],
};

// ⚀
// ⚁
// ⚂
// ⚃
// ⚄
// ⚅
// ♾